---
version: "3.8"
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=iapssdb
    networks:
      - iapps-internal
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    image: maven:3.9.7-amazoncorretto-17
    working_dir: /iapps
    command: bash -c "mvn clean install && java -jar target/IAppsReader.jar"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/iapssdb
      - spring.datasource.username=postgres
      - spring.datasource.password=root
    ports:
      - 8080:8080
    volumes:
      - "./:/iapps"
    networks:
      - iapps-internal
    depends_on:
      - postgres

volumes:
  postgres-data: 
  
networks:
  iapps-internal:
    external: false
